# Generated by Django 2.2 on 2022-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_created',
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
